SRC = CoarseGrainedSynchroList.c \
	FineGrainedSynchroList.c \
	LazySkiplist.c	\
	LazySynchroList.c \
	Skiplist.c \
	LockFreeSkiplist.c \
	NonBlockingList.c \
	LockFreeList.c 

include ../Makefile.in
